services:
  api:
    container_name: game-event-api
    build: api
    ports:
      - 8800:8800
    environment:
      - POSTGRES_DB=game-events
    networks:
      - game-event-network
    depends_on:
      db:
        condition: service_healthy
  rabbitmq:
    container_name: game-event-queue
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=game-event-002
    ports:
      - 5672:5672
    networks:
      - game-event-network
  db:
    container_name: game-event-db
    image: postgres
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - game-event-network
    environment:
      - POSTGRES_DB=game-events
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 10
secrets:
  db-password:
    file: db/password.txt
networks:
  game-event-network:
volumes:
  db-data: